# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

###

# 用户提交周绩效申请
POST http://localhost:8080/api/application
token: e7effab3c1171cb851869125383974fe94314492df0357ca5c843c6b64826124bee59555fcc4b851acd295d64de7d1fb
Content-Type: application/json

{
  "dcRecord": {
    "applicant": {
      "id": 5
    },
    "auditor": {
      "id": 1
    },
    "week": 5,
    "dvalue": 2
  },
  "acItems": [
    {
      "ac": 1,
      "reason": "test1"
    },
    {
      "ac": 1,
      "reason": "test2"
    },
    {
      "ac": 1,
      "reason": "test3"
    }
  ]
}

###

# 获取指定用户的周报
GET http://localhost:8080/api/report/1
token: e7effab3c1171cb851869125383974fe94314492df0357ca5c843c6b64826124bee59555fcc4b851acd295d64de7d1fb

###

# 分页获取指定用户的申请
GET http://localhost:8080/api/application/2/page=0
token: e7effab3c1171cb851869125383974fe94314492df0357ca5c843c6b64826124bee59555fcc4b851acd295d64de7d1fb
Content-Type: application/json

###

# 分页获取指定用户的申请
GET http://localhost:8080/api/application/2/page=1
token: e7effab3c1171cb851869125383974fe94314492df0357ca5c843c6b64826124bee59555fcc4b851acd295d64de7d1fb
Content-Type: application/json

###



