# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

###

# 添加申请
POST http://localhost:8080/api/application
token: 380a1b4ec47c6a4df4ea74219768ceeb5bc86f332bad13f92b9d526aef606107a3239c241100972f2e484270ddc56bc5
Content-Type: application/json

{
  "application": {
    "applicant": {
      "id": 1
    },
    "auditor": {
      "id": 1
    },
    "month": 2,
    "week": 2,
    "dc": 2
  },
  "acItems": [
    {
      "ac": 1,
      "reason": "组会汇报"
    },
    {
      "ac": 1,
      "reason": "论文评审"
    },
    {
      "ac": 1,
      "reason": "组会评审"
    }
  ]
}



###

# 获取指定用户的周报
GET http://localhost:8080/api/report/2
token: 380a1b4ec47c6a4df4ea74219768ceeb5bc86f332bad13f92b9d526aef606107a3239c241100972f2e484270ddc56bc5

###

# 分页获取指定用户的申请
GET http://localhost:8080/api/application/2/page=0
token: 380a1b4ec47c6a4df4ea74219768ceeb5bc86f332bad13f92b9d526aef606107a3239c241100972f2e484270ddc56bc5
Content-Type: application/json


###

# 分页获取指定用户的申请
GET http://localhost:8080/api/application/1/page=0
token: 380a1b4ec47c6a4df4ea74219768ceeb5bc86f332bad13f92b9d526aef606107a3239c241100972f2e484270ddc56bc5
Content-Type: application/json

###

# 获取审核人待审核申请
GET http://localhost:8080/api/pending_audit/1
token: 380a1b4ec47c6a4df4ea74219768ceeb5bc86f332bad13f92b9d526aef606107a3239c241100972f2e484270ddc56bc5
Content-Type: application/json

###